baseURL = 'https://projects.vincdub.com/'
languageCode = 'fr-FR'
title = 'Vincent DUBOIS'
copyright = "Copyright &copy; 2023 - Vincent DUBOIS"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 1
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = false

[languages]
  [languages.fr.params]
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    tagline = "Bâtiment & Data Science"
    weight = 1
  [languages.en.params]
    disabled = true
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    tagline = "Construction & Data Science"
    weight = 1


# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Vincent DUBOIS"
    github = "VincDub/vincdub.github.io"
    #gitlab = "username"
    linkedin = "vincent-dubois-417b4017a"
    #facebook = "username"
    #twitter = "ds_says"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    #tagline = "Bâtiment & Data Science"
    description = "Valoriser les données du bâtiment"
    site_logo = "/img/logo.svg#float"
    #images = [""] #This is used for opengraph/twitter cards.
    #customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

# uncomment to enable the Tags link on the main toolbar
 [[menu.main]]
   identifier = "tags"
   name = "Tags"
   url = "/tags"
   weight = 1

# uncomment to enable the Categories link on the main toolbar
 [[menu.main]]
   identifier = "categories"
   name = "Catégories"
   url = "/categories"
   weight = 1
